[project]
name = "render-mbtiles-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi[all]>=0.115.12",
    "pymbtiles>=0.5.0",
    "ruff>=0.11.13",
    "uvicorn[standard]>=0.34.3",
]
